export const ASCENSION_MATERIALS = {
  0: { SHELL: 0, ELITE_MATERIAL: 0, SPECIALTY_MATERIAL: 0, COMMON: 0, COMMON_RARITY: 0 },
  1: { SHELL: 5000, ELITE_MATERIAL: 0, SPECIALTY_MATERIAL: 0, COMMON: 4, COMMON_RARITY: 2 },
  2: { SHELL: 10000, ELITE_MATERIAL: 3, SPECIALTY_MATERIAL: 4, COMMON: 4, COMMON_RARITY: 3 },
  3: { SHELL: 15000, ELITE_MATERIAL: 6, SPECIALTY_MATERIAL: 8, COMMON: 8, COMMON_RARITY: 3 },
  4: { SHELL: 20000, ELITE_MATERIAL: 9, SPECIALTY_MATERIAL: 12, COMMON: 4, COMMON_RARITY: 4 },
  5: { SHELL: 40000, ELITE_MATERIAL: 12, SPECIALTY_MATERIAL: 16, COMMON: 8, COMMON_RARITY: 4 },
  6: { SHELL: 80000, ELITE_MATERIAL: 20, SPECIALTY_MATERIAL: 20, COMMON: 4, COMMON_RARITY: 5 },
};

export const TALENT_MATERIALS = {
  1: { SHELL: 0, WEEKLY_MATERIAL: 0, WEAPON_MATERIAL: 0, WEAPON_RARITY: 0, COMMON_MATERIAL: 0, COMMON_RARITY: 0 },
  2: { SHELL: 1500, WEEKLY_MATERIAL: 0, WEAPON_MATERIAL: 2, WEAPON_RARITY: 2, COMMON_MATERIAL: 2, COMMON_RARITY: 2 },
  3: { SHELL: 2000, WEEKLY_MATERIAL: 0, WEAPON_MATERIAL: 3, WEAPON_RARITY: 2, COMMON_MATERIAL: 3, COMMON_RARITY: 2 },
  4: { SHELL: 4500, WEEKLY_MATERIAL: 0, WEAPON_MATERIAL: 2, WEAPON_RARITY: 3, COMMON_MATERIAL: 2, COMMON_RARITY: 3 },
  5: { SHELL: 6000, WEEKLY_MATERIAL: 0, WEAPON_MATERIAL: 3, WEAPON_RARITY: 3, COMMON_MATERIAL: 3, COMMON_RARITY: 3 },
  6: { SHELL: 16000, WEEKLY_MATERIAL: 0, WEAPON_MATERIAL: 3, WEAPON_RARITY: 4, COMMON_MATERIAL: 2, COMMON_RARITY: 4 },
  7: { SHELL: 30000, WEEKLY_MATERIAL: 1, WEAPON_MATERIAL: 5, WEAPON_RARITY: 4, COMMON_MATERIAL: 3, COMMON_RARITY: 4 },
  8: { SHELL: 50000, WEEKLY_MATERIAL: 1, WEAPON_MATERIAL: 2, WEAPON_RARITY: 5, COMMON_MATERIAL: 2, COMMON_RARITY: 5 },
  9: { SHELL: 70000, WEEKLY_MATERIAL: 1, WEAPON_MATERIAL: 3, WEAPON_RARITY: 5, COMMON_MATERIAL: 3, COMMON_RARITY: 5 },
  10: { SHELL: 100000, WEEKLY_MATERIAL: 1, WEAPON_MATERIAL: 6, WEAPON_RARITY: 5, COMMON_MATERIAL: 4, COMMON_RARITY: 5 },
};

export const TALENT_INHERENT_MATERIALS = {
  1: { SHELL: 10000, WEEKLY_MATERIAL: 1, WEAPON_MATERIAL: 3, WEAPON_RARITY: 3, COMMON_MATERIAL: 3, COMMON_RARITY: 3 },
  2: { SHELL: 20000, WEEKLY_MATERIAL: 1, WEAPON_MATERIAL: 3, WEAPON_RARITY: 4, COMMON_MATERIAL: 3, COMMON_RARITY: 4 },
};

export const TALENT_SIDE_MATERIALS = {
  1: { SHELL: 50000, WEEKLY_MATERIAL: 0, WEAPON_MATERIAL: 3, WEAPON_RARITY: 4, COMMON_MATERIAL: 3, COMMON_RARITY: 4 },
  2: { SHELL: 100000, WEEKLY_MATERIAL: 1, WEAPON_MATERIAL: 3, WEAPON_RARITY: 5, COMMON_MATERIAL: 3, COMMON_RARITY: 5 },
};